{% set version = "0.10.0" %}

package:
  name: aioice
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/aioice/aioice-{{ version }}.tar.gz
  sha256: 25dfdcbacb89de0e2eac41e96a872499c37a9eb74fa22a0e92d8ac1a0a9141af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - dnspython >=2.0.0
    - ifaddr >=0.2.0

test:
  commands:
    - pip check
  imports:
    - aioice
  requires:
    - pip
    - python ={{ python_min }}


about:
  home: https://github.com/aiortc/aioice
  summary: An implementation of Interactive Connectivity Establishment (RFC 5245)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
